[workspace]
members=[
    "catpuccin-schotter",
    "sidwellr-schotter/schotter1",
    "sidwellr-schotter/schotter2",
    "sidwellr-schotter/schotter3",
    "sidwellr-schotter/schotter4",
]
resolver="2"
